// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_ye8ziQ2R17X8SKXE4Acl-DhK9IC41Y',
    appId: '1:313445609333:android:d2dd0134854cbbcbe06d3c',
    messagingSenderId: '313445609333',
    projectId: 'sumary-2cfcd',
    storageBucket: 'sumary-2cfcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08lnZWhimdfmlXi5005R_xLgfZjRQj08',
    appId: '1:313445609333:ios:e889a7b569bd7a77e06d3c',
    messagingSenderId: '313445609333',
    projectId: 'sumary-2cfcd',
    storageBucket: 'sumary-2cfcd.appspot.com',
    androidClientId: '313445609333-ejlq43tb8nhd8g0ahoecuk8157r3hv8v.apps.googleusercontent.com',
    iosClientId: '313445609333-92elffhkvidocclgift59a7pmqb7an8a.apps.googleusercontent.com',
    iosBundleId: 'vn.sumaryApp',
  );
}
